export const categorySubCategoriesMap: Record<string, string[]> = {
  'Soups': ['Veg', 'Chicken', 'HSM Signature (Goat)'],
  'HSM House Made Momo': ['Veg', 'Chicken'],
  'Momo': ['Veg', 'Chicken'],
  'Veg Tandoor': [],
  'Non-Veg Tandoor': [],
  'Veg Appetizers': ['Veg', 'Gobi', 'Paneer', 'Mushroom'],
  'Non-Veg Appetizers': ['Egg', 'Chicken', 'Goat', 'Fish', 'Shrimp'],
  'Biryani': ['Veg', 'Paneer', 'Egg', 'Chicken', 'Goat', 'Fish', 'Shrimp'],
  'Biryani (Bone-In)': ['Veg', 'Paneer', 'Egg', 'Chicken', 'Goat', 'Fish', 'Shrimp'],
  'Family Pack Biryani': ['Veg', 'Paneer', 'Egg', 'Chicken', 'Goat', 'Fish', 'Shrimp'],
  'Family Pack Biryani (To-Go Only)': ['Veg', 'Paneer', 'Egg', 'Chicken', 'Goat', 'Fish', 'Shrimp'],
  'Indo Chinese': ['Veg', 'Paneer', 'Gobi', 'Egg', 'Chicken', 'Fish', 'Shrimp'],
  'Indo Chinese (Appetizers / Entrees)': ['Veg', 'Paneer', 'Gobi', 'Egg', 'Chicken', 'Fish', 'Shrimp'],
  'Fried Rice': ['Veg', 'Paneer', 'Egg', 'Chicken', 'Shrimp', 'Goat'],
  'Noodles': ['Veg', 'Paneer', 'Egg', 'Chicken', 'Shrimp'],
  'Veg Curries': ['Veg', 'Paneer', 'Mushroom'],
  'Egg Curries': [],
  'Non-Veg Curries': ['Chicken', 'Goat', 'Fish', 'Shrimp'],
  'Kids Menu': [],
  'Drinks': [],
  'Dessert': [],
  'Bread and Rice': [],
  'Breads & Rice': [],
  'Extras': [],
  'Mandi': ['Paneer', 'Egg', 'Chicken', 'Goat', 'Shrimp', 'Nalli Gosht', 'Juicy', 'Arabian', 'Malai', 'Charminar Grilled'],
  'Dosas': ['Vegetarian Dosa', 'Spicy Non-Veg Dosa', 'Village Special Dosa', 'Kids Special Dosa', 'Extras (for Dosa)'],
  'Chaat Specials': [],
  'Beer': ['Bottle Beer', 'East Indian Beer', 'Draft Beer'],
  'Wine': ['Sparkling', 'White', 'Red', 'Sweet', 'Fruit', 'House Special'],
};
